### ISSUE TITLE
Intray review command question

### ISSUE THREAD

**Issue by chiroptical** [NorfairKing/intray#10]
I believe it is a design decision that answering `n` during `intray review` would not cycle through to the next item. My belief is based on the behavior of `intray {show,done}`.

Would it make sense to simply end the review session upon entry of `n`?

Feel free to close this if I misunderstood the design decisions. Otherwise, I would be happy to contribute :smile:

**Comment by NorfairKing** [comment]
Hi @chiroptical 

You got the design decision right.

I'm a bit confused about your question, because in my understanding, that's already how it works:
https://github.com/NorfairKing/intray/blob/master/intray-cli/src/Intray/Cli/Commands/Review.hs#L40

**Comment by chiroptical** [comment]
Ahh, I see what is going on. You have `[yN]` and I assumed `n` was the default. If you don't submit anything it will fall through to `review`.

**Comment by chiroptical** [comment]
I'll let you decide but the simplest solution is just `"" -> stop`. If you want it to be more robust, I could bring in `Data.Char` and filter out space characters from `res`

**Comment by NorfairKing** [comment]
I would currently not want to make the change that you suggest, but for the wrong reasons.
My reasoning is that whenever my window is resized during an `intray review`, and my terminal is all messed up and doesn't show anything except my cursor anymore, I can still press `Enter` to "fix" it.
What you're describing is probably more intuitive, so let's do it, but please also tell me what else I can do with a messed-up terminal :p

**Comment by chiroptical** [comment]
I think depends on what terminal you are using. I think `Ctrl-L` should redraw but I can't get my terminal in a state where this is an issue to test.

**Comment by NorfairKing** [comment]
`C-l` works in the prompt but not in `intray review`.
To reproduce, try resizing your window to something very small and then back to normal.

**Comment by chiroptical** [comment]
I tried that. I was expecting it to be an issue but it isn't. I tried both XFCE Terminal and Kitty.

**Comment by NorfairKing** [comment]
I'm using URXVT and it's an issue. We can just ignore this and continue with what you had in mind.

**Comment by chiroptical** [comment]
Behavior corrected in #11, thanks @NorfairKing
