### ISSUE TITLE
store.json missing after stack install

### ISSUE THREAD

**Issue by llattila** [NorfairKing/intray#12]
Cloned the repository and used `stack install` to install the software. Using `intray add yyy` throws:

`intray: /home/zzzzzzz/.local/share/intray/store.json: openFd: does not exist (No such file or directory)`

The file does not exists on the system, nor the folder.

**Comment by NorfairKing** [comment]
Found the bug, fixed in development.
This had to do with making a lock file in a directory that doesn't exist yet.
Typical stuff :(
I added a regression test so this shouldn't happen ever again.
