### ISSUE TITLE
Invalid route on self-hosted web server

### ISSUE THREAD

**Issue by Ninlives** [NorfairKing/intray#13]
This is the config of my server:
```nix
{ ... }: {
      imports = [
        (import "${
            builtins.fetchGit {
              url = "https://github.com/NorfairKing/intray.git";
              rev = "e0ab102d2646eeec5c9fe2d1b9235873213ebf6c";
            }
          }/nix/nixos-module.nix" { envname = "private"; })
      ];

      services.intray.private = {
        enable = true;
        web-hosts = [ web-url ];
        api-hosts = [ api-url ];
        inherit web-port api-port;
        admins = [ username ];
        freeloaders = [ username ];
      };

      security.acme.acceptTerms = true;
      security.acme.email = email;
      services.nginx.enable = true;
}
```

The server is up but all links on index page resolve to `https://localhost:${web-port}`, which is apparently unusable.

**Comment by NorfairKing** [comment]
Hm this is strange.
This is what mine look like:
```
    services.intray.production = {
        enable = true;
        web-hosts = [ "intray.eu" "intray.cs-syd.eu" ];
        api-hosts = [ "api.intray.eu" "api.intray.cs-syd.eu" ];
        web-port = 8000;
        api-port = 8001;
        log-level = "LevelWarn";
  };
```

Could it be that you used something that starts with `https://` in the `hosts` lists?

**Comment by Ninlives** [comment]
> Could it be that you used something that starts with `https://` in the `hosts` lists?

No, I checked `/etc/hosts` on my laptop and server, neither has such entry

**Comment by Ninlives** [comment]
@NorfairKing Do you have any other configurations related to nginx?

**Comment by NorfairKing** [comment]
@Ninlives I meant the `api-hosts` and `web-hosts` lists.
I do have this config, but it shouldn't be relevant for intray:

```
      services.nginx = {
        enable = true;
        recommendedGzipSettings = true;
        recommendedOptimisation = true;
        recommendedProxySettings = true;
        # recommendedTlsSettings = true;
        # We need these for android
        sslProtocols = "TLSv1 TLSv1.1 TLSv1.2 TLSv1.3";
        sslCiphers = "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS:!3DES";

        appendHttpConfig = ''
          ssl_ecdh_curve prime256v1:secp384r1;
        '';
      };
```

**Comment by Ninlives** [comment]
@NorfairKing I also do not have such element in the hosts list...

**Comment by Ninlives** [comment]
> @Ninlives I meant the `api-hosts` and `web-hosts` lists.
> I do have this config, but it shouldn't be relevant for intray I think..:
> 
> ```
>       services.nginx = {
>         enable = true;
>         recommendedGzipSettings = true;
>         recommendedOptimisation = true;
>         recommendedProxySettings = true;
>         # recommendedTlsSettings = true;
>         # We need these for android
>         sslProtocols = "TLSv1 TLSv1.1 TLSv1.2 TLSv1.3";
>         sslCiphers = "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS:!3DES";
> 
>         appendHttpConfig = ''
>           ssl_ecdh_curve prime256v1:secp384r1;
>         '';
>       };
> ```

Oh it is relevant :cry: , my guess is that `proxy_redirect off` should be set, but I don't have time to verify it now.

**Comment by NorfairKing** [comment]
Feel free to reopen if this is still relevant.

**Comment by StevenXL** [comment]
Where can I find what `recommendedProxySettings` are?

**Comment by StevenXL** [comment]
> Where can I find what `recommendedProxySettings` are?

I found them here (https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-servers/nginx/default.nix) but after setting `proxy_redirect off` the app is still generating links to `localhost:3002`.
