### ISSUE TITLE
Elaborate on the android app

### ISSUE THREAD

**Issue by voidus** [NorfairKing/intray#22]
https://intray.cs-syd.eu/ says that there is an android app, but I cannot find any further information.

Things that would be interesting:
- Is it open source (I guess not, since it's not in the repository)
- Is it free or only included in the subscription?
- How is it installed/updated?
- Can it be used with a self-hosted server.

**Comment by NorfairKing** [comment]
There is an app, and it is free and open-source here: https://gitlab.com/Norfair/intray-android/

HOWEVER: I don't recommend it, because I don't trust it enough to work reliably.
Instead I recommend you use the web interface from your phone.

**Comment by voidus** [comment]
Ah, I didn't think to look at gitlab, thanks for the info :)
