### ISSUE TITLE
Getting sqlite foreign key constraint error?

### ISSUE THREAD

**Issue by chiroptical** [NorfairKing/intray#4]
Hey, I am getting,

```
intray: SQLite3 returned ErrorConstraint while attempting to perform step: FOREIGN KEY constraint failed
```

whenever I try to run a command after a recent update.

**Comment by NorfairKing** [comment]
Hi @chiroptical This is strange and unexpected.
Could you (backup and) remove `~/.local/share/intray` and see if that fixes things?

**Comment by chiroptical** [comment]
Yup, that does it! Thank you!

**Comment by NorfairKing** [comment]
Great. Make sure you didn't lose any unsynced items by double-checking your backup :)
