### ISSUE TITLE
cli: Wrong Cookie Gets Saved When Used w/ Cloudflare

### ISSUE THREAD

**Issue by prikhi** [NorfairKing/intray#6]
Hey, I set `intray-server` up on a VPS which is secured by Cloudflare. When you use Cloudflare's proxy/SSL service, they add a `__cfduid` cookie to responses. It seems like intray just records the first cookie it sees, so the actual JWT cookie never gets saved:

```
$ intray login
$ cd ~/.cache/intray
$ cat session.cookie
__cfduid=REDACTED; Path=/; Expires=Tue, 19-May-2020 11:07:48 GMT; Domain=.REDACTED.com; HttpOnly; Secure
$ intray sync
Sync failed:
FailureResponse 
  (Request {requestPath = (BaseUrl {baseUrlScheme = Https, baseUrlHost = "REDACTED", baseUrlPort = 443, baseUrlPath = ""},"/intray/sync"), requestQueryString = fromList [], requestBody = Just ((),application/json;charset=utf-8), requestAccept = fromList [application/json;charset=utf-8,application/json], requestHeaders = fromList [("Authorization","Bearer REDACTED")], requestHttpVersion = HTTP/1.1, requestMethod = "POST"}) 
  (Response {responseStatusCode = Status {statusCode = 401, statusMessage = "Unauthorized"}, responseHeaders = fromList [("Date","Sun, 19 Apr 2020 11:07:52 GMT"),("Content-Length","0"),("Connection","keep-alive"),("Set-Cookie","__cfduid=REDACTED; expires=Tue, 19-May-20 11:07:52 GMT; path=/; domain=.REDACTED; HttpOnly; SameSite=Lax"),("CF-Cache-Status","DYNAMIC"),("Expect-CT","max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""),("Server","cloudflare"),("CF-RAY","58662a17dcecbe78-RIC"),("cf-request-id","0233b8a2e60000be782f99f200000001")], responseHttpVersion = HTTP/1.1, responseBody = ""})
```

If I disable the proxy service and login via `http` instead of https, it works and then I can switch cloudflare back on. It seems like the android client is not affected by this issue.

**Comment by NorfairKing** [comment]
Same response here:
Could the problem be here: https://github.com/NorfairKing/intray/blob/master/intray-cli/src/Intray/Cli/Commands/Login.hs#L37
I never understood what the second header was for...

**Comment by NorfairKing** [comment]
The same will be true for tickler.cs-syd.eu

**Comment by NorfairKing** [comment]
In the meantime you're encouraged to use the instance at intray.eu so that I will be the one taking care of stuff like this.

**Comment by prikhi** [comment]
I messed around with code a bit and found a dirty-ish way to get around this.

I changed `PostLogin` in `Intray.API` from `SetCookie` to `Text`(not sure why there's no ByteString instance for FromHttpApiData):
```haskell
"login" 
    :> ReqBody '[ JSON] LoginForm 
    :> PostNoContent '[ JSON] (Headers '[ Header "Set-Cookie" (Text)] NoContent)
```
And the corresponding client function in `Intray.Client`:
```haskell
clientPostLogin 
    :: LoginForm 
    -> ClientM (Headers '[Header "Set-Cookie" Text] NoContent)
```

Now in `Intray.Cli.Command.Login`, we have to split up the cookie lines, parse each, and then find the `JWT-Cookie` cookie:
```haskell
Header setCookie -> do
    let cookies = parseSetCookie . encodeUtf8 <$> T.lines setCookie
        jwtCookie = find ((== "JWT-Cookie") . setCookieName) cookies
    case jwtCookie of
        Nothing ->
            liftIO $ die "No JWT-Cookie was found in the Set-Cookie session header."
        Just setCookie_ ->
            saveSession setCookie_
```

And now `intray login` sets `~/.cache/intray/session.cookie` correctly.

**Comment by NorfairKing** [comment]
> I changed PostLogin in Intray.API from SetCookie to Text

Why was this necessary?
For the rest, could you make a PR?

**Comment by prikhi** [comment]
> > I changed PostLogin in Intray.API from SetCookie to Text
> 
> Why was this necessary?

The header is a single `Set-Cookie` header with each cookie delimited by newlines. Servant didn't like me specifying something like `Header "Set-Cookie" [SetCookie]` so I just went with Text for the quick fix. 

Would you prefer if I tried making a `newtype SetCookies = SetCookies { fromSetCookies :: [SetCookie] }` type and write a custom `FromHttpApiData` instance for it?

> For the rest, could you make a PR?

Yup, building it up now but gotta figure out how to make it work with the server's `servePostLogin` handler...

**Comment by NorfairKing** [comment]
> The header is a single Set-Cookie header with each cookie delimited by newlines. Servant didn't like me specifying something like Header "Set-Cookie" [SetCookie] so I just went with Text for the quick fix.

So the client must be able to handle send any number of `SetCookie` cookies? Is there an opper-bound on it? Then we can just use that number of `Header`s. Otherwise this sounds like a good idea:
```
newtype SetCookies = SetCookies { fromSetCookies :: [SetCookie] }
```

**Comment by prikhi** [comment]
At first, I tried using multiple `Header "Set-Cookie" SetCookie` declarations in the API type, but after printing each of them out, they just returned the same `__cfuid` cookie :disappointed: 

I'm guessing it's because cloudflare injects its cookies into the existing `Set-Cookie` header instead of adding a separate header, but I'm not too well versed on Servant's Header/Cookie parsing.

What module should I stick the `SetCookies` type in?

**Comment by NorfairKing** [comment]
I just had another look through the servant APIs and a closer look at the way http headers work.
I changed my mind and I now think that using `Text` is fine, as long as that doesn't crash when you have 1. no SetCookie or 2. an empty SetCookie. 
Does that sound reasonable?

**Comment by prikhi** [comment]
> I just had another look through the servant APIs and a closer look at the way http headers work.
> I changed my mind and I now think that using `Text` is fine, as long as that doesn't crash when you have 1. no SetCookie or 2. an empty SetCookie.
> Does that sound reasonable?

:+1: I've got every package building now but I'm not sure how to test no setcookie or a blank setcookie.

Right now, the CLI calls `die` if it can't find the `JWT-Cookie` cookie, and calls `die` if the header is missing(like before).

**Comment by NorfairKing** [comment]
> Right now, the CLI calls die if it can't find the JWT-Cookie cookie, and calls die if the header is missing(like before).

That's good enough!

**Comment by prikhi** [comment]
See PR #7
